using System.Collections.Generic;
using UnityEngine;
using UnityEngine.Tilemaps;

/* Initially generated by ChatGPT, then modified to fit our needs.
* This component spawns hazards based on a tilemap. Each tile in the tilemap corresponds to a hazard prefab.
*/
public class HazardSpawner : MonoBehaviour
{
    [System.Serializable]
    public class HazardMapping
    {
        public string name;                 // just for readability in Inspector
        public TileBase markerTile;         // tile painted in HazardMarkers tilemap
        public GameObject hazardPrefab;     // prefab to spawn
        public Vector3 worldOffset;         // e.g. bubble top-left anchor = (0.5, -0.5, 0)
        public bool clearMarkerAfterSpawn = true;
    }

    [Header("References")]
    [SerializeField] private Tilemap hazardMarkerTilemap;
    [SerializeField] private Transform hazardsParent;

    [Header("Marker -> Prefab mappings")]
    [SerializeField] private List<HazardMapping> mappings = new List<HazardMapping>();

    private void Start()
    {
        SpawnAllHazards();
    }

    public void SpawnAllHazards()
    {
        if (hazardMarkerTilemap == null)
        {
            Debug.LogError("HazardSpawner: hazardMarkerTilemap is not assigned.");
            return;
        }

        if (hazardsParent == null)
        {
            Debug.LogError("HazardSpawner: hazardsParent is not assigned.");
            return;
        }

        // Build a quick lookup dictionary
        Dictionary<TileBase, HazardMapping> lookup = new Dictionary<TileBase, HazardMapping>();
        foreach (var m in mappings)
        {
            if (m.markerTile != null && m.hazardPrefab != null && !lookup.ContainsKey(m.markerTile))
            {
                lookup.Add(m.markerTile, m);
            }
        }

        // Tighten bounds to used cells only
        hazardMarkerTilemap.CompressBounds();
        BoundsInt bounds = hazardMarkerTilemap.cellBounds;

        foreach (Vector3Int cellPos in bounds.allPositionsWithin)
        {
            TileBase tile = hazardMarkerTilemap.GetTile(cellPos);
            if (tile == null) continue;

            if (!lookup.TryGetValue(tile, out HazardMapping mapping))
                continue;

            Vector3 spawnPos = hazardMarkerTilemap.GetCellCenterWorld(cellPos) + mapping.worldOffset;

            Instantiate(mapping.hazardPrefab, spawnPos, Quaternion.identity, hazardsParent);

            if (mapping.clearMarkerAfterSpawn)
            {
                hazardMarkerTilemap.SetTile(cellPos, null);
            }
        }
    }
}