using System;
using System.Collections;
using Cinemachine;
using UnityEngine;
using UnityEngine.InputSystem;
// Initially generated by ClaudeCode, modified by me to add the actual cutscene content and polish the code. 
public class OpeningCutscene : MonoBehaviour
{
    [Header("Dialog")]
    [SerializeField] private CutsceneDirector cutsceneDirector;
    [SerializeField] private CutsceneDirector.DialogLine[] preWiggleLines;
    [SerializeField] private CutsceneDirector.DialogLine[] postWiggleLines;
    [SerializeField] private CutsceneDirector.DialogLine[] finalLines;

    [Header("Wiggle Free")]
    [SerializeField] private CanvasGroup wigglePrompt;
    [SerializeField] private float promptFadeDuration = 0.3f;
    [SerializeField] private int pressesNeeded = 8;
    [SerializeField] private float wiggleSpriteHoldTime = 0.12f;

    [Header("Monger")]
    [SerializeField] private SpriteRenderer mongerRenderer;
    [SerializeField] private Sprite mongerHoldingIdle;
    [SerializeField] private Sprite mongerWiggle;
    [SerializeField] private Sprite mongerEscaped;

    [Header("Bobby")]
    [SerializeField] private Transform bobbyTransform;
    [SerializeField] private Animator bobbyAnim;
    [SerializeField] private string bobbySwimAnim = "BobbySwim";
    [SerializeField] private float waterSurfaceY = 0f;
    [SerializeField] private float bobbyHopSpeed = 4f;
    [SerializeField] private float bobbyHopDuration = 0.25f;
    [SerializeField] private float bobbyGravity = 10f;
    [SerializeField] private float bobbyMaxFallSpeed = 8f;
    [SerializeField] private Transform bobbySwimOffTarget;
    [SerializeField] private Transform bobbyReturnTarget;
    [SerializeField] private float bobbySwimSpeed = 3f;

    [Header("Player")]
    [SerializeField] private Transform playerTransform;
    [SerializeField] private Transform playerStartPosition;
    [SerializeField] private Transform playerWaterEntryTarget;
    [SerializeField] private float playerArcHeight = 1.5f;
    [SerializeField] private Transform playerEscapeTarget;
    [SerializeField] private float playerEscapeSpeed = 5f;

    [Header("Camera")]
    [SerializeField] private CinemachineVirtualCamera virtualCamera;
    [SerializeField] private Transform boatCameraTarget;

    [Header("Next Room")]
    [SerializeField] private string nextScene;
    [SerializeField] private string nextSpawnId;

    private InputAction _interactAction;
    private player _playerScript;
    private SpriteRenderer[] _playerRenderers;
    private SpriteRenderer _playerSprite;

    [SerializeField] private GameObject UI;

    private void Start()
    {
        _interactAction = InputSystem.actions.FindAction("Interact");
        _playerScript = GameObject.FindWithTag("Player")?.GetComponent<player>();
        _playerSprite = playerTransform?.GetComponent<SpriteRenderer>();

        if (_playerScript != null)
        {
            _playerScript.canMove = false;
            _playerScript.inputEnabled = false;
        }

        if (playerTransform != null)
        {
            if (playerStartPosition != null)
                playerTransform.position = playerStartPosition.position;
            _playerRenderers = playerTransform.GetComponentsInChildren<SpriteRenderer>(true);
            foreach (var sr in _playerRenderers) sr.enabled = false;
        }

        if (mongerRenderer != null && mongerHoldingIdle != null)
            mongerRenderer.sprite = mongerHoldingIdle;

        if (wigglePrompt != null)
        {
            wigglePrompt.alpha = 0f;
            wigglePrompt.gameObject.SetActive(false);
        }

        if (virtualCamera != null && boatCameraTarget != null)
            virtualCamera.Follow = boatCameraTarget;

        MusicManager.Instance?.StopBGMusic();
        StartCoroutine(RunCutscene());
    }

    private IEnumerator RunCutscene()
    {
        bool done = false;
        cutsceneDirector.Play(preWiggleLines, () => done = true);
        yield return new WaitUntil(() => done);

        yield return StartCoroutine(WiggleFreePhase());

        // Player arcs left and down into the water before the crew reacts
        if (playerWaterEntryTarget != null)
        {
            if (virtualCamera != null) virtualCamera.Follow = playerTransform;
            float arcDuration = Vector2.Distance(playerTransform.position, playerWaterEntryTarget.position) / playerEscapeSpeed;
            yield return StartCoroutine(ArcMove(playerTransform, playerWaterEntryTarget.position, arcDuration, playerArcHeight, FacePlayer));
        }

        done = false;
        cutsceneDirector.Play(postWiggleLines, () => done = true);
        yield return new WaitUntil(() => done);

        yield return StartCoroutine(ChaseSequence());

        // Final line — keep the camera where it is; don't let CutsceneDirector pan to the boat
        cutsceneDirector.controlsCamera = false;
        done = false;
        cutsceneDirector.Play(finalLines, () => done = true);
        yield return new WaitUntil(() => done);
        cutsceneDirector.controlsCamera = true;

        // Restore player to a normal playable state before loading (same as Main_Menu.startButtonPressed)
        if (_playerScript != null)
        {
            _playerScript.canMove = true;
            _playerScript.inputEnabled = true;
        }

        MusicManager.Instance?.PlayBGMusic();
        UI.SetActive(true);
        RoomTransitionManager.Instance?.GoToRoom(nextScene, nextSpawnId);
    }

    private IEnumerator WiggleFreePhase()
    {
        yield return null; // skip one frame so last dialog press doesn't count as a wiggle

        yield return StartCoroutine(FadePrompt(1f));

        int presses = 0;
        Coroutine wiggleReset = null;

        while (presses < pressesNeeded)
        {
            if (_interactAction != null && _interactAction.WasPressedThisFrame())
            {
                presses++;
                if (mongerRenderer != null && mongerWiggle != null)
                    mongerRenderer.sprite = mongerWiggle;
                if (wiggleReset != null) StopCoroutine(wiggleReset);
                wiggleReset = StartCoroutine(ResetWiggleSprite());
            }
            yield return null;
        }

        if (wiggleReset != null) StopCoroutine(wiggleReset);
        if (mongerRenderer != null && mongerEscaped != null)
            mongerRenderer.sprite = mongerEscaped;

        if (_playerRenderers != null)
            foreach (var sr in _playerRenderers) sr.enabled = true;

        yield return StartCoroutine(FadePrompt(0f));
    }

    private IEnumerator ResetWiggleSprite()
    {
        yield return new WaitForSecondsRealtime(wiggleSpriteHoldTime);
        if (mongerRenderer != null && mongerHoldingIdle != null)
            mongerRenderer.sprite = mongerHoldingIdle;
    }

    private IEnumerator ChaseSequence()
    {
        bobbyTransform.SetParent(null);

        // Enable animator now so Bobby animates through the whole dive (same as Bobby.cs ActivatePhase2)
        if (bobbyAnim != null) bobbyAnim.enabled = true;

        // Hop off the boat — face upward (head up = jumping)
        float elapsed = 0f;
        while (elapsed < bobbyHopDuration)
        {
            elapsed += Time.unscaledDeltaTime;
            float vy = Mathf.Lerp(bobbyHopSpeed, 0f, elapsed / bobbyHopDuration);
            bobbyTransform.position += Vector3.up * vy * Time.unscaledDeltaTime;
            FaceBobby(Vector3.up);
            yield return null;
        }

        // Fall to water — face downward (headfirst dive, same as Bobby.cs DiveSequence)
        float fallVelocity = 0f;
        while (bobbyTransform.position.y > waterSurfaceY)
        {
            fallVelocity = Mathf.Min(fallVelocity + bobbyGravity * Time.unscaledDeltaTime, bobbyMaxFallSpeed);
            bobbyTransform.position += Vector3.down * fallVelocity * Time.unscaledDeltaTime;
            Vector3 p = bobbyTransform.position;
            p.y = Mathf.Max(p.y, waterSurfaceY);
            bobbyTransform.position = p;
            FaceBobby(Vector3.down);
            yield return null;
        }

        // Play swim animation and chase the player off-screen; camera follows player
        if (bobbyAnim != null && !string.IsNullOrEmpty(bobbySwimAnim))
            bobbyAnim.Play(bobbySwimAnim);
        if (virtualCamera != null) virtualCamera.Follow = playerTransform;

        Coroutine bobbyGo = StartCoroutine(MoveToTarget(bobbyTransform, bobbySwimOffTarget.position, bobbySwimSpeed, FaceBobby));
        Coroutine playerGo = StartCoroutine(MoveToTarget(playerTransform, playerEscapeTarget.position, playerEscapeSpeed, FacePlayer));
        yield return bobbyGo;
        yield return playerGo;

        yield return new WaitForSecondsRealtime(0.5f);

        // Bobby swims back; camera stays where it is
        yield return StartCoroutine(MoveToTarget(bobbyTransform, bobbyReturnTarget.position, bobbySwimSpeed, FaceBobby));
    }

    // Matches player.cs: flipX from velocity.x, rotate by atan2 with 180° flip if facing left
    private void FacePlayer(Vector3 direction)
    {
        if (_playerSprite == null || direction.sqrMagnitude < 0.0001f) return;
        if (direction.x != 0)
            _playerSprite.flipX = direction.x < 0;
        float angle = Mathf.Atan2(direction.y, direction.x) * Mathf.Rad2Deg;
        if (_playerSprite.flipX) angle -= 180f;
        playerTransform.rotation = Quaternion.Euler(0f, 0f, angle);
    }

    // Matches Bobby.cs: atan2 direction with -90° offset (sprite head points up)
    private void FaceBobby(Vector3 direction)
    {
        if (bobbyTransform == null || direction.sqrMagnitude < 0.0001f) return;
        float angle = Mathf.Atan2(direction.y, direction.x) * Mathf.Rad2Deg - 90f;
        bobbyTransform.rotation = Quaternion.Euler(0f, 0f, angle);
    }

    private IEnumerator MoveToTarget(Transform obj, Vector3 target, float speed, Action<Vector3> facing = null)
    {
        while (Vector2.Distance(obj.position, target) > 0.05f)
        {
            Vector3 dir = (target - obj.position).normalized;
            facing?.Invoke(dir);
            obj.position = Vector3.MoveTowards(obj.position, target, speed * Time.unscaledDeltaTime);
            yield return null;
        }
        obj.position = target;
    }

    // Moves obj along a parabolic arc; facing is called with the tangent direction each frame
    private IEnumerator ArcMove(Transform obj, Vector3 target, float duration, float arcHeight, Action<Vector3> facing = null)
    {
        Vector3 start = obj.position;
        Vector3 prevPos = start;
        float elapsed = 0f;
        while (elapsed < duration)
        {
            elapsed = Mathf.Min(elapsed + Time.unscaledDeltaTime, duration);
            float t = elapsed / duration;
            Vector3 pos = Vector3.Lerp(start, target, t);
            pos.y += arcHeight * Mathf.Sin(t * Mathf.PI);
            Vector3 dir = pos - prevPos;
            if (dir.sqrMagnitude > 0.0001f) facing?.Invoke(dir.normalized);
            prevPos = pos;
            obj.position = pos;
            yield return null;
        }
        obj.position = target;
    }

    private IEnumerator FadePrompt(float target)
    {
        if (wigglePrompt == null) yield break;
        wigglePrompt.gameObject.SetActive(true);
        float start = wigglePrompt.alpha;
        float elapsed = 0f;
        while (elapsed < promptFadeDuration)
        {
            elapsed += Time.unscaledDeltaTime;
            wigglePrompt.alpha = Mathf.Lerp(start, target, elapsed / promptFadeDuration);
            yield return null;
        }
        wigglePrompt.alpha = target;
        if (target == 0f) wigglePrompt.gameObject.SetActive(false);
    }
}
