using System.Collections;
using Cinemachine;
using UnityEngine;
using UnityEngine.Rendering.Universal;
using UnityEngine.SceneManagement;

/**
* RoomTransitionManager
* - Initially generated by ChatGPT as a response to a request for a scene transition manager that works with the provided ExitTrigger and SpawnPoint scripts.
* - Manages scene transitions and player placement at spawn points.
* - Designed to be a persistent singleton that can be called from any scene.
* - Works in tandem with ExitTrigger and SpawnPoint components.
*/
public class RoomTransitionManager : MonoBehaviour
{
    public static RoomTransitionManager Instance { get; private set; }

    [Header("References")]
    [SerializeField] private Transform player; // Drag your persistent Player here

    [Header("Timing")]
    [SerializeField] private float postLoadDelay = 0.02f; // tiny delay so scene objects initialize

    [Header("Safety")]
    [SerializeField] private bool zeroPlayerVelocityOnSpawn = true;

    [Header("Camera")]
    [SerializeField] private CinemachineVirtualCamera virtualCamera;

    [Header("Fade")]
    [SerializeField] private CanvasGroup fadePanel;
    [SerializeField] private float normalFadeDuration = 0.3f;
    [SerializeField] private float deathFadeDuration = 1.0f;

    [Header("Default Spawn Settings")]
    [SerializeField] private string defaultScene = "level_1";
    // Change these values in the Inspector or hardcode them here to fit your starting room
    [SerializeField] private Vector3 defaultSpawnPosition = new Vector3(0f, 0f, 0f);
    private CinemachineConfiner2D cinemachineConfiner2D;
    private PolygonCollider2D roomBoundsCollider;
    private RoomCameraSettings roomCameraSettings;

    private player _playerScript;
    private string _pendingSpawnId;
    private bool _isTransitioning;
    public bool IsTransitioning => _isTransitioning;

    // Checkpoint state (persists across scenes)
    private bool _hasCheckpoint = false;
    private string _checkpointScene;
    private Vector3 _checkpointPosition;

    public void SetCheckpoint(string scene, Vector3 position)
    {
        _hasCheckpoint = true;
        _checkpointScene = scene;
        _checkpointPosition = position;
    }

    private void Awake()
    {
        if (Instance != null && Instance != this)
        {
            Destroy(gameObject);
            return;
        }
        Debug.Log(virtualCamera);
        Instance = this;
        _playerScript = player.GetComponent<player>();
        cinemachineConfiner2D = virtualCamera.GetComponent<CinemachineConfiner2D>();
        if (cinemachineConfiner2D == null)
        {
            Debug.LogError("RoomTransitionManager: No CinemachineConfiner2D found on the assigned virtual camera.");
        }
    }

    private void Start()
    {
        zoomCamera();
        StartCoroutine(DoThingNextFrame()); // Wait a frame to ensure everything is initialized
        cinemachineConfiner2D.InvalidateCache(); // Ensure confiner updates to new bounds
    }

    public void zoomCamera()
    {
        // Adjust camera settings here based on new room's RoomCameraSettings component
        roomCameraSettings = GameObject.Find("RoomCameraSettings")?.GetComponent<RoomCameraSettings>();
        if (roomCameraSettings != null)
        {
            int computedRefResX = roomCameraSettings.GetReferenceResolutionX();
            int computedRefResY = roomCameraSettings.GetReferenceResolutionY();
            virtualCamera.m_Lens.OrthographicSize = roomCameraSettings.GetOrthoSize();
            // Assuming you have a PixelPerfectCamera component on the same GameObject as the virtual camera
            PixelPerfectCamera ppc = Camera.main.GetComponent<PixelPerfectCamera>();
            if (ppc != null)
            {
                ppc.refResolutionX = computedRefResX;
                ppc.refResolutionY = computedRefResY;
            }
            else
            {
                Debug.LogWarning("RoomTransitionManager: No PixelPerfectCamera found on the main camera. Cannot apply reference resolution settings.");
            }
        }
    }
    public void GoToRoom(string destinationSceneName)
    {
        GoToRoom(destinationSceneName, "default");
    }

    public void GoToRoom(string destinationSceneName, string destinationSpawnId)
    {
        if (_isTransitioning) return;

        _pendingSpawnId = destinationSpawnId;
        StartCoroutine(LoadRoomRoutine(destinationSceneName, normalFadeDuration));
    }

    //Call this when the player dies
    public void RespawnAtDefault()
    {
        if (_isTransitioning) return;

        if (_hasCheckpoint)
        {
            _pendingSpawnId = "CheckpointRespawn";
            StartCoroutine(LoadRoomRoutine(_checkpointScene, deathFadeDuration));
            return;
        }

        // Use a specific keyword to tell the spawner to use the hardcoded coordinates
        _pendingSpawnId = "RespawnDefault";
        StartCoroutine(LoadRoomRoutine(defaultScene, deathFadeDuration));
    }

    private IEnumerator DoThingNextFrame()
    {
        yield return null; // wait 1 frame
    }

    private IEnumerator FadeToBlack(float duration)
    {
        if (fadePanel == null) yield break;
        fadePanel.alpha = 0f;
        float elapsed = 0f;
        while (elapsed < duration)
        {
            elapsed += Time.deltaTime;
            fadePanel.alpha = Mathf.Clamp01(elapsed / duration);
            yield return null;
        }
        fadePanel.alpha = 1f;
    }

    private IEnumerator FadeFromBlack(float duration)
    {
        if (fadePanel == null) yield break;
        fadePanel.alpha = 1f;
        float elapsed = 0f;
        while (elapsed < duration)
        {
            elapsed += Time.deltaTime;
            fadePanel.alpha = 1f - Mathf.Clamp01(elapsed / duration);
            yield return null;
        }
        fadePanel.alpha = 0f;
    }

    private IEnumerator LoadRoomRoutine(string sceneName, float fadeDuration)
    {
        _isTransitioning = true;
        if (_playerScript != null) _playerScript.inputEnabled = false;

        yield return StartCoroutine(FadeToBlack(fadeDuration));

        AsyncOperation loadOp = SceneManager.LoadSceneAsync(sceneName, LoadSceneMode.Single);

        while (!loadOp.isDone)
        {
            yield return null;
        }

        // Tiny delay so objects in the new scene finish Awake/Start
        if (postLoadDelay > 0f)
            yield return new WaitForSeconds(postLoadDelay);

        // Set new roomBounds for the CinemachineConfiner2D
        roomBoundsCollider = GameObject.Find("RoomBounds")?.GetComponent<PolygonCollider2D>();
        if (roomBoundsCollider == null)
        {
            Debug.LogError("RoomTransitionManager: No GameObject named 'RoomBounds' with a PolygonCollider2D found in the loaded scene.");
            yield return StartCoroutine(FadeFromBlack(fadeDuration));
            if (_playerScript != null) _playerScript.inputEnabled = true;
            _isTransitioning = false;
            yield break;
        }
        cinemachineConfiner2D.m_BoundingShape2D = roomBoundsCollider;
        cinemachineConfiner2D.InvalidateCache();
        zoomCamera();
        yield return null; // Wait a frame for the camera to update
        cinemachineConfiner2D.InvalidateCache(); // Ensure confiner updates to new bounds

        PlacePlayerAtPendingSpawn();

        // Reset health after death respawn, once screen is black and scene is loaded
        if (_pendingSpawnId == "RespawnDefault" || _pendingSpawnId == "CheckpointRespawn")
        {
            player.GetComponent<Attackable>()?.ResetHealth();
        }

        yield return StartCoroutine(FadeFromBlack(fadeDuration));

        if (_playerScript != null) _playerScript.inputEnabled = true;
        _isTransitioning = false;
    }

    private void PlacePlayerAtPendingSpawn()
    {
        if (player == null)
        {
            Debug.LogError("RoomTransitionManager: Player reference is missing.");
            return;
        }

        // --- Intercept checkpoint respawn ---
        if (_pendingSpawnId == "CheckpointRespawn")
        {
            player.position = _checkpointPosition;
            ResetPlayerVelocity();
            return;
        }

        // --- Intercept the hardcoded default spawn ---
        if (_pendingSpawnId == "RespawnDefault")
        {
            player.position = defaultSpawnPosition;
            ResetPlayerVelocity();
            return;
        }

        // Find all SpawnPoint components in the loaded scene
        ExitTrigger[] spawnPoints = Object.FindObjectsByType<ExitTrigger>(FindObjectsSortMode.None);

        if (spawnPoints == null || spawnPoints.Length == 0)
        {
            Debug.LogError("RoomTransitionManager: No SpawnPoint objects found in loaded scene.");
            return;
        }

        ExitTrigger matchedSpawn = null;

        foreach (ExitTrigger sp in spawnPoints)
        {
            if (sp.SpawnId == _pendingSpawnId)
            {
                matchedSpawn = sp;
                break;
            }
        }

        if (matchedSpawn == null)
        {
            Debug.LogWarning($"RoomTransitionManager: Could not find spawn ID '{_pendingSpawnId}'. Using first available spawn.");
            matchedSpawn = spawnPoints[0];
        }

        matchedSpawn._spawnedInside = true;
        player.position = matchedSpawn.transform.position;
        ResetPlayerVelocity();
    }

    //Helper method to clean up the velocity reset logic
    private void ResetPlayerVelocity()
    {
        if (zeroPlayerVelocityOnSpawn)
        {
            Rigidbody2D rb = player.GetComponent<Rigidbody2D>();
            if (rb != null)
            {
                rb.linearVelocity = Vector2.zero;
                rb.angularVelocity = 0f;
            }
        }
    }
}