using System.Collections;
using UnityEngine;
using UnityEngine.SceneManagement;

/**
* RoomTransitionManager
* - Initially generated by ChatGPT as a response to a request for a scene transition manager that works with the provided ExitTrigger and SpawnPoint scripts.
* - Manages scene transitions and player placement at spawn points.
* - Designed to be a persistent singleton that can be called from any scene.
* - Works in tandem with ExitTrigger and SpawnPoint components.
*/
public class RoomTransitionManager : MonoBehaviour
{
    public static RoomTransitionManager Instance { get; private set; }

    [Header("References")]
    [SerializeField] private Transform player; // Drag your persistent Player here

    [Header("Timing")]
    [SerializeField] private float postLoadDelay = 0.02f; // tiny delay so scene objects initialize

    [Header("Safety")]
    [SerializeField] private bool zeroPlayerVelocityOnSpawn = true;

    private string _pendingSpawnId;
    private bool _isTransitioning;

    private void Awake()
    {
        if (Instance != null && Instance != this)
        {
            Destroy(gameObject);
            return;
        }

        Instance = this;
    }

    public void GoToRoom(string destinationSceneName, string destinationSpawnId)
    {
        if (_isTransitioning) return;

        _pendingSpawnId = destinationSpawnId;
        StartCoroutine(LoadRoomRoutine(destinationSceneName));
    }

    private IEnumerator LoadRoomRoutine(string sceneName)
    {
        _isTransitioning = true;

        // (Optional later) disable player input here
        // (Optional later) play fade-out here

        AsyncOperation loadOp = SceneManager.LoadSceneAsync(sceneName, LoadSceneMode.Single);

        while (!loadOp.isDone)
        {
            yield return null;
        }

        // Tiny delay so objects in the new scene finish Awake/Start
        if (postLoadDelay > 0f)
            yield return new WaitForSeconds(postLoadDelay);

        PlacePlayerAtPendingSpawn();

        // (Optional later) play fade-in here
        // (Optional later) re-enable input here

        _isTransitioning = false;
    }

    private void PlacePlayerAtPendingSpawn()
    {
        if (player == null)
        {
            Debug.LogError("RoomTransitionManager: Player reference is missing.");
            return;
        }

        // Find all SpawnPoint components in the loaded scene
        Spawnpoint[] spawnPoints = Object.FindObjectsByType<Spawnpoint>(FindObjectsSortMode.None);

        if (spawnPoints == null || spawnPoints.Length == 0)
        {
            Debug.LogError("RoomTransitionManager: No SpawnPoint objects found in loaded scene.");
            return;
        }

        Spawnpoint matchedSpawn = null;

        foreach (Spawnpoint sp in spawnPoints)
        {
            if (sp.SpawnId == _pendingSpawnId)
            {
                matchedSpawn = sp;
                break;
            }
        }

        if (matchedSpawn == null)
        {
            Debug.LogWarning($"RoomTransitionManager: Could not find spawn ID '{_pendingSpawnId}'. Using first available spawn.");
            matchedSpawn = spawnPoints[0];
        }

        player.position = matchedSpawn.transform.position;

        if (zeroPlayerVelocityOnSpawn)
        {
            Rigidbody2D rb = player.GetComponent<Rigidbody2D>();
            if (rb != null)
            {
                rb.linearVelocity = Vector2.zero;
                rb.angularVelocity = 0f;
            }
        }
    }
}